### ISSUE TITLE
模板下载中... ERROR  TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Combat88** [savokiss/vue-preset-mobile#1]
您好，在使用你的模板时报这个错

**Comment by Combat88** [comment]
![image](https://user-images.githubusercontent.com/28495544/65655967-b0385c80-e050-11e9-9f5f-3cb5b197bf33.png)

**Comment by savokiss** [comment]
用最新版本试下哈~ 注意 vue-cli 版本不要太老~
